function [y1] = flex_middle_x(x1)
%FLEX_MIDDLE_X neural network simulation function.
%
% Auto-generated by MATLAB, 08-Aug-2019 10:16:36.
% 
% [y1] = flex_middle_x(x1) takes these arguments:
%   x = 1xQ matrix, input #1
% and returns:
%   y = 1xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 59.8362059788327;
x1_step1.gain = 0.155349197573605;
x1_step1.ymin = -1;

% Layer 1
b1 = [-2.2245597195708639582;-0.34674795466363939056;5.245674488407933822;0.72727293031286377456;-3.3093035310380258807];
IW1_1 = [2.0845242509434029898;0.7758805193820874635;6.9905914800481223637;1.5134605167364894029;-4.0788907092582249447];

% Layer 2
b2 = -0.93712076807630273478;
LW2_1 = [-0.78831492841922834458 0.73530940908431197123 -1.990352379084076917 -0.84131877040278113533 -2.9041764656642734543];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.215308210362026;
y1_step1.xoffset = 0;

% ===== SIMULATION ========

% Dimensions
Q = size(x1,2); % samples

% Input 1
xp1 = mapminmax_apply(x1,x1_step1);

% Layer 1
a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);

% Layer 2
a2 = repmat(b2,1,Q) + LW2_1*a1;

% Output 1
y1 = mapminmax_reverse(a2,y1_step1);
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
  x = bsxfun(@minus,y,settings.ymin);
  x = bsxfun(@rdivide,x,settings.gain);
  x = bsxfun(@plus,x,settings.xoffset);
end
