function [y1] = flex_middle_x(x1)
%FLEX_MIDDLE_X neural network simulation function.
%
% Auto-generated by MATLAB, 26-Jul-2019 16:45:03.
% 
% [y1] = flex_middle_x(x1) takes these arguments:
%   x = 1xQ matrix, input #1
% and returns:
%   y = 1xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 63.7686290805757;
x1_step1.gain = 0.180004641181732;
x1_step1.ymin = -1;

% Layer 1
b1 = [0.33817070831375273254;-0.84669174046030981629;-0.2605571878002693742;-0.38141184824692142552;0.16173207543037612655];
IW1_1 = [-0.068894256566981781909;1.438401992331384216;2.3594939859051695663;-1.6196311392752416047;0.24455658930203816315];

% Layer 2
b2 = -0.043191212306247520059;
LW2_1 = [-0.092757582698537538457 -1.121543503384504481 1.008768159174812773 0.84916989358531957954 0.10847290831350939189];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.21791678561312;
y1_step1.xoffset = 6.4874392649439;

% ===== SIMULATION ========

% Dimensions
Q = size(x1,2); % samples

% Input 1
xp1 = mapminmax_apply(x1,x1_step1);

% Layer 1
a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);

% Layer 2
a2 = repmat(b2,1,Q) + LW2_1*a1;

% Output 1
y1 = mapminmax_reverse(a2,y1_step1);
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
  x = bsxfun(@minus,y,settings.ymin);
  x = bsxfun(@rdivide,x,settings.gain);
  x = bsxfun(@plus,x,settings.xoffset);
end
