function [y1] = flex_index_y(x1)
%FLEX_INDEX_Y neural network simulation function.
%
% Auto-generated by MATLAB, 25-Jul-2019 12:02:53.
% 
% [y1] = flex_index_y(x1) takes these arguments:
%   x = 1xQ matrix, input #1
% and returns:
%   y = 1xQ matrix, output #1
% where Q is the number of samples.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====

% Input 1
x1_step1.xoffset = 51.2976233418694;
x1_step1.gain = 0.123506750467203;
x1_step1.ymin = -1;

% Layer 1
b1 = [-1.0367241644881912688;13.31946432445840145];
IW1_1 = [1.5638118876128828116;19.328508194492869166];

% Layer 2
b2 = -0.35241202744968508354;
LW2_1 = [-1.0011881817766226099 -0.1638748827743463643];

% Output 1
y1_step1.ymin = -1;
y1_step1.gain = 0.0711365377582372;
y1_step1.xoffset = 73.5704473889436;

% ===== SIMULATION ========

% Dimensions
Q = size(x1,2); % samples

% Input 1
xp1 = mapminmax_apply(x1,x1_step1);

% Layer 1
a1 = tansig_apply(repmat(b1,1,Q) + IW1_1*xp1);

% Layer 2
a2 = repmat(b2,1,Q) + LW2_1*a1;

% Output 1
y1 = mapminmax_reverse(a2,y1_step1);
end

% ===== MODULE FUNCTIONS ========

% Map Minimum and Maximum Input Processing Function
function y = mapminmax_apply(x,settings)
  y = bsxfun(@minus,x,settings.xoffset);
  y = bsxfun(@times,y,settings.gain);
  y = bsxfun(@plus,y,settings.ymin);
end

% Sigmoid Symmetric Transfer Function
function a = tansig_apply(n,~)
  a = 2 ./ (1 + exp(-2*n)) - 1;
end

% Map Minimum and Maximum Output Reverse-Processing Function
function x = mapminmax_reverse(y,settings)
  x = bsxfun(@minus,y,settings.ymin);
  x = bsxfun(@rdivide,x,settings.gain);
  x = bsxfun(@plus,x,settings.xoffset);
end
